version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: /api
    expose:
      - "3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: /api
      FASTAPI_BASE_URL: http://backend:8000/api
    depends_on:
      - backend

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
